- hosts: all
  sudo: true
  tasks:
    - name: add a new user
      user: name=testuser2 state=present

    - name: add authorized keys
      file: dest=/home/testuser2/.ssh/authorized_keys state=directory
