- hosts: all
  sudo: true

  vars:
    - username:  testuser4  #put username 
    - homedir:   /home/hm_system_users/{{username}}
    - pubkeydir: /developments/ansible/ansible-ssh-keygen/foo.txt
  tasks:
    - name: add a new user
      user: name={{username}} state=present home={{homedir}}

    - name: mkdir .ssh
      file: dest={{homedir}}/.ssh/ state=directory owner={{username}} group={{username}} mode=700 

    - name: add authorized keys
      file: dest={{homedir}}/.ssh/authorized_keys state=touch owner={{username}} group={{username}} mode=600

    - name: copy publickey
      copy: src={{pubkeydir}} dest={{homedir}}/.ssh/authorized_keys
