- hosts: all
  sudo: true

  vars:
    - username:  komiya.tomohiro3 #put username
    - homedir:   /home/{{username}}
  tasks:
    - name: add a new user
      user: name={{username}} state=present home={{homedir}}

    - name: mkdir .ssh
      file: dest={{homedir}}/.ssh/ state=directory owner={{username}} group={{username}} mode=700 

    - name: add authorized keys
      file: dest={{homedir}}/.ssh/authorized_keys state=touch owner={{username}} group={{username}} mode=600

    - name: add authoried_keys
      authorized_key: user={{username}}  key="{{lookup('file', '~/.ssh/id_rsa.pub')}}"
